language: java

jdk:
  - oraclejdk8

sudo: false

install: true

script:
  - mvn clean install -Dmaven.javadoc.skip -Dmaven.test.skip=true

after_success:
  - mvn clean test jacoco:report coveralls:report